version: 2.1

executors:
  simple:
    docker:
      - image: circleci/jdk8:0.1.1

commands:
  install_maven:
    description: "Install Maven"
    steps:
      - run: apt-get -y update && apt-get -y install maven

  compile:
    description: "Invoke maven compile"
    steps:
      - run: mvn compile

  test:
    description: "Invoke maven unit tests"
    steps:
      - run: mvn test

  install_codacy_coverage_reporter_dependencies:
    description: "Download Codacy coverage reporter dependencies"
    steps:
      - run: apt-get -y update && apt-get -y install curl jq

  download_codacy_coverage_reporter:
    description: "Download Codacy coverage reporter"
    parameters:
      reporter_jar:
        type: string
        default: ~/reporter.jar
    steps:
      - run: wget -O << parameters.reporter_jar >> $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

  report_coverage_to_codacy:
    description: "Report coverage to Codacy"
    parameters:
      reporter_jar:
        type: string
        default: ~/reporter.jar
      jacoco_file:
        type: string
        default: target/site/jacoco/jacoco.xml
    steps:
      - run: java -jar << parameters.reporter_jar >> report -l Java -r << parameters.jacoco_file >>

jobs:
  build:
    executor: simple
    steps:
      - checkout
      - install_maven
      - compile

  report_coverage:
    executor: simple
    steps:
      - checkout
      - install_codacy_coverage_reporter_dependencies
      - download_codacy_coverage_reporter
      - install_maven
      - test
      - report_coverage_to_codacy

workflows:
  full:
    jobs:
      - build
      - report_coverage:
          requires:
            - build