version: 2.1

commands:
  install_maven:
    description: "Install Maven"
    steps:
      - run: apt-get -y update && apt-get -y install maven

  compile:
    description: "Invoke maven compile"
    steps:
      - run: mvn compile

  test:
    description: "Invoke maven unit tests"
    steps:
      - run: mvn test

  download_codacy_coverage_reporter:
    description: "Download Codacy coverage reporter"
    parameters:
      reporter_jar:
        type: string
    steps:
      - run: wget -O << parameters.reporter_jar >> $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

  report_coverage:
    description: "Report coverage to Codacy"
    parameters:
      reporter_jar:
        type: string
      jacoco_file:
        type: string
    steps:
      - run: java -jar << parameters.reporter_jar >> report -l Java -r << parameters.jacoco.file >>

jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - install_maven
      - compile

  report_coverage:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - download_codacy_coverage_reporter:
        reporter_jar: "~/reporter.jar"
      - test
      - report_coverage:
        reporter_jar: "~/reporter.jar"
        jacoco_file: "target/site/jacoco/jacoco.xml"

workflows:
  full:
    jobs:
      - build
      - report_coverage:
          requires:
            - build