version: 2.1

jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run: mvn clean install -DskipTests

  test:
    steps:
      - checkout
      - run: mvn test

workflows:
  build_and_test:
    jobs:
      - build
      - test