version: 2.1

jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run:
        name: Build
        command:
          apt-get -y update
          apt-get -y install maven
          mvn clean install -DskipTests

  test:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run:
        name: Run tests
        command:
          apt-get -y update
          apt-get -y install maven
          mvn test
          wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
          java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/report/jacoco.xml

workflows:
  build_and_test:
    jobs:
      - build
      - test