version: 2.1

executors:
  simple:
    docker:
      - image: circleci/jdk8:0.1.1

commands:
  install_maven:
    description: "Install Maven"
    steps:
      - run: apt-get -y update && apt-get -y install maven

  compile:
    description: "Invoke maven compile"
    steps:
      - run: mvn compile

  test:
    description: "Invoke maven unit tests"
    steps:
      - run: mvn test

jobs:
  build:
    executor: simple
    steps:
      - checkout
      - install_maven
      - compile

  report_coverage:
    executor: simple
    steps:
      - checkout
      - install_maven
      - test

workflows:
  full:
    jobs:
      - build
      - report_coverage:
          requires:
            - build